export const SET_IMAGE_URL = 'SET_IMAGE_URL'
export const SET_TIMER = 'SET_TIMER'
export const CLEAR_TIMER = 'CLEAR_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
export const FETCH_IMAGES = 'FETCH_IMAGES'